
image: node:18.16.0-alpine3.18

cache:
  paths:
    - node_modules/

test:
  script:
    - npm install
    - npm run test

build:
    script:
        - npm run build

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
